apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tealc-install
  labels:
    project: tealc
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: tealc-install
      timeout: "2h30m0s"
      workspaces:
        - name: pipeline-ws
          workspace: pipeline-ws
      taskSpec:
        workspaces:
          - name: pipeline-ws
        steps:
          - name: tealc-install
            env:
              - name: GIT_CRYPT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: git-crypt-key
                    key: key
            image: quay.io/tealc/tealc-ee:latest
            script: |
              export CURRENT_DIR=$(workspaces.pipeline-ws.path)/tealc
              git clone https://github.com/skodjob/tealc.git $CURRENT_DIR
              echo $GIT_CRYPT_SECRET | base64 -d > "$CURRENT_DIR/crypt-key"
              cd $CURRENT_DIR && git crypt unlock crypt-key
              cd $CURRENT_DIR && ansible-playbook install/tealc-play.yaml --tags="infra,strimzi-infra,odh" -v
  finally:
    - name: notify-slack
      when:
        - input: $(tasks.status)
          operator: in
          values: ["Failed"]
      taskRef:
        name: send-to-webhook-slack
      params:
        - name: webhook-secret
          value: webhook-secret
        - name: message
          value: "Pipeline `$(context.pipeline.name)`:`$(context.pipelineRun.name)` failed!"
---

apiVersion: polling.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: tealc-repository
  labels:
    project: tealc
spec:
  url: https://github.com/skodjob/tealc.git
  ref: main
  frequency: 5m
  type: github
  pipelineRef:
    serviceAccountName: pipeline
    name: tealc-install
    workspaces:
      - name: pipeline-ws
        emptyDir: {}
  auth:
    secretRef:
      name: github-secret
    key: TOKEN
