---
- include_tasks: prepare_access_twitter.yaml
  loop:
    - "{{ workers.source_cluster }}"
  loop_control:
    loop_var: worker

- name: Create Argo applications for Strimzi twitter
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_argo_namespace }}"
    state: present
    src: "files/argo/applications/strimzi-twitter-app.yaml"

- name: Create Twitter app related Tekton pipelines
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_ci_namespace }}"
    state: present
    src: "{{ item }}"
  with_fileglob: 'files/tekton/pipelines/twitter-app/*.yaml'

- name: Sleep for 20 seconds and continue with play (wait tull everything is setup)
  wait_for:
    timeout: 20

- name: Create Twitter app Tekton pipeline runs
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_ci_namespace }}"
    state: present
    src: "files/tekton/pipelines/twitter-app/run/pipeline-runs.yaml"
