apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: strimzi-deployment-image-update-task
  labels:
    project: tealc
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  workspaces:
    - name: task-ws
  steps:
    - name: tealc-clone
      image: quay.io/wire/alpine-git
      script: |
        export CURRENT_DIR=$(workspaces.task-ws.path)/tealc
        git clone https://github.com/ExcelentProject/tealc.git $CURRENT_DIR
    # This is needed to be sure that all images are pushed, because the webhook pointing to the operator image
    - name: wait-for-push
      image: quay.io/tealc/apophis:latest
      script: |
        sleep 5m
    - name: images-update
      env:
        - name: CURRENT_DEPLOYMENT_REPO
          value: "https://github.com/ExcelentProject/sokar"
        - name: SHARED_YAML_BUNDLE_FILES
          value: "./strimzi/cluster-operator-common/"
        - name: YAML_BUNDLE_PATHS
          value: "./strimzi/zookeeper-mode/cluster-operator/,./strimzi/kraft-mode/cluster-operator"
        - name: TARGET_ORG_REPO
          value: "quay.io/strimzi"
        - name: BRANCH
          value: main
        - name: SYNC_CRD_REPO
          value: "https://github.com/strimzi/strimzi-kafka-operator"
        - name: SYNC_CRD_PATH
          value: "packaging/install/cluster-operator"
        - name: GITHUB_USERNAME
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: USERNAME
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: TOKEN
      image: quay.io/tealc/apophis:latest
      script: |
        $(workspaces.task-ws.path)/tealc/image-update/strimzi-image-update.sh
        echo "[INFO] Done!"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: strimzi-deployment-image-update-pipeline
  labels:
    project: tealc
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: strimzi
      taskRef:
        name: strimzi-deployment-image-update-task
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
  finally:
    - name: notify-slack
      when:
        - input: $(tasks.status)
          operator: in
          values: ["Failed"]
      taskRef:
        name: send-to-webhook-slack
      params:
        - name: webhook-secret
          value: webhook-secret
        - name: message
          value: "Pipeline `$(context.pipeline.name)`:`$(context.pipelineRun.name)` failed!"

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: strimzi-deployment-image-update-trigger-template
  labels:
    project: tealc
spec:
  params:
    - name: message
      description: Message from quay.io
      default: empty
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: strimzi-deployment-image-update-
        labels:
          app: tealc
      spec:
        pipelineRef:
          name: strimzi-deployment-image-update-pipeline
        workspaces:
          - name: pipeline-ws
            volumeClaimTemplate:
              metadata:
                name: strimzi-pvc
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 500Mi


---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: strimzi-deployment-image-update-triggerbinding
  labels:
    project: tealc
spec:
  params:
    - name: message
      value: $(body)

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: strimzi-image-update-event-listener
  labels:
    listener: tealc
    project: tealc
spec:
  triggers:
    - name: strimzi-deployment-image-update-webhook
      bindings:
        - ref: strimzi-deployment-image-update-triggerbinding
      template:
        ref: strimzi-deployment-image-update-trigger-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            containers:
              - resources:
                  limits:
                    memory: "64Mi"
                    cpu: "50m"

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-strimzi-image-update-event-listener
  labels:
    project: tealc
spec:
  to:
    kind: Service
    name: el-strimzi-image-update-event-listener
    weight: 100
  port:
    targetPort: http-listener
