---
- name: Delete agro openshift
  block:
    - name: Delete ReportPortal instance
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
        namespace: "{{ rp_namespace }}"
        state: absent
        template: templates/report_portal/install/rp-instance.yaml.j2

    - name: Delete ReportPortal subscription
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
        state: absent
        src: files/report_portal/install/rp-subscription.yaml

    - name: Delete ReportPortal namespace on Infra cluster
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
        name: "{{ rp_namespace }}"
        api_version: v1
        kind: Namespace
        state: absent

    - name: Delete ReportPotal access secret
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
        namespace: "{{ infra_ci_namespace }}"
        name: "{{ rp_secret_name }}"
        state: absent
        kind: Secret

    - name: Delete ReportPortal CSV on Infra cluster
      shell: "oc delete csv -n {{ openshift_operators_namespace }} $(oc get csv -n openshift-operators | grep reportportal | cut -d' ' -f1)"
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}/{{ infra_context_name }}"
      ignore_errors: true

    - name: Delete ReportPortal namespace on Infra cluster
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
        name: "{{ rp_namespace }}"
        api_version: v1
        kind: Namespace
        state: absent

  when: not is_kubernetes
