apiVersion: v1
kind: ServiceAccount
metadata:
  name: tealc-metrics-collector
  labels:
    app: tealc-metrics-collector
---
kind: Service
apiVersion: v1
metadata:
  name: tealc-metrics-collector
  labels:
    app: tealc-metrics-collector
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
  selector:
    app: tealc-metrics-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tealc-metrics-collector
  labels:
    app: tealc-metrics-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tealc-metrics-collector
  template:
    metadata:
      labels:
        app: tealc-metrics-collector
        tealc/kind: thor-exporter
    spec:
      serviceAccountName: tealc-metrics-collector
      containers:
        - name: tealc-metrics-collector
          image: quay.io/tealc/metrics-collector:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "1000m"
            requests:
              memory: "128Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 8080
              name: data
              protocol: TCP
  strategy:
    type: Recreate
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: tealc
  name: thor-metrics
spec:
  podMetricsEndpoints:
    - path: /data
      port: http
  selector:
    matchLabels:
      tealc/kind: thor-exporter
