apiVersion: v1
kind: ServiceAccount
metadata:
  name: tealc-metrics-collector
  labels:
    app: tealc-metrics-collector
---
kind: Service
apiVersion: v1
metadata:
  name: tealc-metrics-collector
  labels:
    app: tealc-metrics-collector
spec:
  ports:
    - port: 8080
      name: metrics
      protocol: TCP
      targetPort: 8080
  selector:
    app: tealc-metrics-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tealc-metrics-collector
  labels:
    app: tealc-metrics-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tealc-metrics-collector
  template:
    metadata:
      labels:
        app: tealc-metrics-collector
        tealc/kind: thor-exporter
    spec:
      serviceAccountName: tealc-metrics-collector
      containers:
        - name: tealc-metrics-collector
          image: quay.io/tealc/metrics-collector@sha256:d3cef0ead47a03d9c8e3eb3a74ac3475ae36d550f2a159ba3b868709825dad7a
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
  strategy:
    type: Recreate
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: tealc
  name: thor-metrics
spec:
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      tealc/kind: thor-exporter
