############
# Get FIPs #
############
- name: "Collect floating IP for api"
  shell: "oc get secret {{ clusterName }}-install-config -n {{ hive_namespace }} -o=jsonpath='{.data.install-config\.yaml}' | base64 -d | yq '.platform.openstack.apiFloatingIP'"
  register: fip_api_output

- name: "Collect floating IP for apps"
  shell: "oc get secret {{ clusterName }}-install-config -n {{ hive_namespace }} -o=jsonpath='{.data.install-config\.yaml}' | base64 -d | yq '.platform.openstack.ingressFloatingIP'"
  register: fip_apps_output

############################
# Delete ClusterDeployment #
############################
# This is not working properly - https://issues.redhat.com/browse/HIVE-2308
#- name: "Delete {{ clusterName }} MachinePool"
#  kubernetes.core.k8s:
#    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
#    namespace: "{{ hive_namespace }}"
#    state: absent
#    apply: true
##    template: templates/hive/machine-pool.yaml.j2
#    template: ../../../templates/hive/machine-pool.yaml.j2
#    verify_ssl: no
#  loop: "{{ cluster_machine_pools }}"
#  loop_control:
#    loop_var: machine_pool
#  vars:
#    node_type: "{{ machine_pool.node_type }}"
#    node_flavor: "{{ machine_pool.node_flavor }}"
#    node_replicas: "{{ machine_pool.node_replicas }}"

- name: "Delete {{ clusterName }} ClusterDeployment config"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ hive_namespace }}"
    state: absent
    apply: true
    template: templates/hive/cluster-provision.yaml.j2
    verify_ssl: no
  vars:
    install_config_name: "{{ cluster_name }}-install-config"

###############################
# Delete InstallConfig secret #
###############################
- name: "Delete InstallConfig secret for {{ cluster_name }}"
  kubernetes.core.k8s:
    state: absent
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ hive_namespace }}"
    apply: true
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ install_config_name }}"
      data:
        install_config.yaml: "{{ lookup('template', 'templates/hive/install-config.j2' ) | b64encode }}"
  vars:
    install_config_name: "{{ cluster_name }}-install-config"
    fip_apps: "{{ fip_apps_output.stdout }}"
    fip_api: "{{ fip_api_output.stdout }}"

#############################
# Delete DNS records in AWS #
#############################
- name: "Delete AWS DNS command for API of {{ cluster_name }}"
  vars:
    action: "DELETE"
    record_prefix: "api"
    fip: "{{ fip_api_output.stdout }}"
  template:
    src: "templates/hive/aws_record.json.j2"
    dest: "aws_record"
- name: "Update DNS record for API of {{ cluster_name }}"
  shell:  "aws route53 change-resource-record-sets --hosted-zone-id {{ hosted_zone_id }} --change-batch file://aws_record --output json"

- name: "Delete AWS DNS command for APPS of {{ cluster_name }}"
  vars:
    action: "DELETE"
    record_prefix: "*.apps"
    fip: "{{ fip_apps_output.stdout }}"
  template:
    src: "templates/hive/aws_record.json.j2"
    dest: "aws_record"
- name: "Update DNS record for APPS of {{ cluster_name }}"
  shell:  "aws route53 change-resource-record-sets --hosted-zone-id {{ hosted_zone_id }} --change-batch file://aws_record --output json"

###############
# Delete FIPs #
###############
- name: "Delete FIP API"
  shell: "openstack floating ip delete {{ fip_api_output.stdout }}"
  environment:
    OS_CLOUD: "{{ cloud }}"

- name: "Delete FIP apps"
  shell: "openstack floating ip delete {{ fip_apps_output.stdout }}"
  environment:
    OS_CLOUD: "{{ cloud }}"
