---
# defaults file for tealc
infra_monitoring_namespace: tealc
infra_ci_namespace: tealc
infra_argo_namespace: tealc

rp_namespace: report-portal
rp_secret_name: reportportal

openshift_pipelines_namespace: openshift-pipelines
openshift_operators_namespace: openshift-operators
tekton_pipelines_namespace: tekton-pipelines
tekton_operator_namespace: tekton-operator
strimzi_twitter_connector_namespace: strimzi-kafka

is_kubernetes: false

route: empty
access_token: empty

log_sensitive_data: False
