apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clients-deployment-image-update-task
  labels:
    project: tealc
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  workspaces:
    - name: task-ws
  steps:
    - name: tealc-clone
      image: quay.io/rh_integration/strimzi-tools:latest
      script: |
        export CURRENT_DIR=$(workspaces.task-ws.path)/tealc
        git clone https://github.com/ExcelentProject/tealc.git $CURRENT_DIR
    - name: wait-for-push
      image: quay.io/tealc/apophis:latest
      script: |
        sleep 3m
    - name: images-update
      env:
        - name: CURRENT_DEPLOYMENT_REPO
          value: "https://github.com/ExcelentProject/sokar"
        - name: TARGET_ORG_REPO
          value: "quay.io/strimzi-test-clients"
        - name: BRANCH
          value: main
        - name: GITHUB_USERNAME
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: USERNAME
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: TOKEN
      image: quay.io/tealc/apophis:latest
      script: |
        FILE_NAME=strimzi/clients/00-external-clients.yaml $(workspaces.task-ws.path)/tealc/image-update/clients-image-update.sh
        FILE_NAME=strimzi/clients/01-internal-clients.yaml $(workspaces.task-ws.path)/tealc/image-update/clients-image-update.sh
        FILE_NAME=strimzi/twitter-connector/clients/01-verification-clients.yaml $(workspaces.task-ws.path)/tealc/image-update/clients-image-update.sh
        echo "[INFO] Done!"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clients-deployment-image-update-pipeline
  labels:
    project: tealc
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: clients-image-update
      taskRef:
        name: clients-deployment-image-update-task
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: clients-deployment-image-update-trigger-template
  labels:
    project: tealc
spec:
  params:
    - name: message
      description: Message from quay.io
      default: empty
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: clients-deployment-image-update-
        labels:
          app: tealc
      spec:
        pipelineRef:
          name: clients-deployment-image-update-pipeline
        serviceAccountName: pipeline
        workspaces:
          - name: pipeline-ws
            volumeClaimTemplate:
              metadata:
                name: clients-pvc
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: clients-deployment-image-update-triggerbinding
  labels:
    project: tealc
spec:
  params:
    - name: message
      value: $(body)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: clients-deployment-image-update-event-listener
  labels:
    listener: tealc
    project: tealc
spec:
  serviceAccountName: pipeline
  triggers:
    - name: clients-deployment-image-update-webhook
      bindings:
        - ref: clients-deployment-image-update-triggerbinding
      template:
        ref: clients-deployment-image-update-trigger-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-clients-deployment-image-update-event-listener
  labels:
    project: tealc
spec:
  to:
    kind: Service
    name: el-clients-deployment-image-update-event-listener
    weight: 100
  port:
    targetPort: http-listener
