---
- name: Delete Grafana access on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: absent
    template: templates/grafana/grafana-setup.yaml.j2

- name: Delete Grafana access on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ worker.monitoring_namespace }}"
    state: absent
    template: templates/grafana/grafana-setup.yaml.j2
  loop:
    - "{{ workers.source_cluster }}"
    - "{{ workers.target_cluster }}"
  loop_control:
    loop_var: worker

- name: Delete Grafana operator on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: absent
    template: templates/grafana/grafana-operator.yaml.j2

- name: Delete Grafana operator on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ worker.name }}"
    namespace: "{{ worker.monitoring_namespace }}"
    state: absent
    template: templates/grafana/grafana-operator.yaml.j2
  loop:
    - "{{ workers.source_cluster }}"
    - "{{ workers.target_cluster }}"
  loop_control:
    loop_var: worker

- name: Delete Grafana instance on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: absent
    template: templates/grafana/grafana.yaml.j2

- name: Delete Grafana instance on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ worker.name }}"
    namespace: "{{ worker.monitoring_namespace }}"
    state: absent
    template: templates/grafana/grafana.yaml.j2
  loop:
    - "{{ workers.source_cluster }}"
    - "{{ workers.target_cluster }}"
  loop_control:
    loop_var: worker

- name: Remove Alertmanager  configuration for sending alerts on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    state: absent
    template: templates/alert-manager-configuration.yaml.j2
  vars:
    clusterName: "{{ infra_context_name }}"

- name: Remove Alertmanager configuration for sending alerts on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ worker.name }}"
    state: absent
    template: templates/alert-manager-configuration.yaml.j2
  vars:
    clusterName: "{{ worker.name }}"
  loop:
    - "{{ workers.source_cluster }}"
    - "{{ workers.target_cluster }}"
  loop_control:
    loop_var: worker

- name: Delete Grafana dashboards and Prometheus alerts
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: absent
    src: "files/argo/metrics/{{ target_file }}"
  loop:
    - alerts.yaml
    - argo-dashboard-cm.yaml
    - grafana-argo-dashboards.yaml
  loop_control:
    loop_var: target_file

- name: Delete Grafana data-source on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: absent
    template: templates/grafana-data-source.yaml.j2

- name: Delete Grafana data-source on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ worker.name }}"
    namespace: "{{ worker.monitoring_namespace }}"
    state: absent
    template: templates/grafana-data-source.yaml.j2
  loop:
    - "{{ workers.source_cluster }}"
    - "{{ workers.target_cluster }}"
  loop_control:
    loop_var: worker

- name: Delete monitoring namespace on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    name: "{{ infra_monitoring_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent

- name: Delete monitoring namespaces on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ worker.name }}"
    name: "{{ worker.monitoring_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
  loop:
    - "{{ workers.source_cluster }}"
    - "{{ workers.target_cluster }}"
  loop_control:
    loop_var: worker
  