---
- name: Check that 'github_secret_path' is not defined
  fail:
    msg: "Variable 'github_secret_path' is not defined"
  when: github_secret_path is not defined

- name: Check that 'workers' is not defined
  fail:
    msg: "Variable 'workers' is not defined"
  when: workers is not defined

- name: Check that 'kubeconfig_path' is not defined
  fail:
    msg: "Variable 'kubeconfig_path' is not defined"
  when: kubeconfig_path is not defined

- name: Check that 'infra_api_url' is not defined
  fail:
    msg: "Variable 'infra_api_url' is not defined"
  when: infra_api_url is not defined

- name: Check that 'smtp_username' is not defined
  fail:
    msg: "Variable 'smtp_username' is not defined"
  when: smtp_username is not defined