---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: strimzi-deployment-image-update-start
  labels:
    app: tealc
    project: tealc
spec:
  pipelineRef:
    name: strimzi-deployment-image-update-pipeline
  workspaces:
    - name: pipeline-ws
      volumeClaimTemplate:
        metadata:
          name: strimzi-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: drain-cleaner-deployment-image-update-start
  labels:
    app: tealc
    project: tealc
spec:
  pipelineRef:
    name: drain-cleaner-deployment-image-update-pipeline
  workspaces:
    - name: pipeline-ws
      volumeClaimTemplate:
        metadata:
          name: drain-cleaner-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: canary-deployment-image-update-start
  labels:
    app: tealc
    project: tealc
spec:
  pipelineRef:
    name: canary-deployment-image-update-pipeline
  workspaces:
    - name: pipeline-ws
      volumeClaimTemplate:
        metadata:
          name: canary-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clients-deployment-image-update-start
  labels:
    app: tealc
    project: tealc
spec:
  pipelineRef:
    name: clients-deployment-image-update-pipeline
  workspaces:
    - name: pipeline-ws
      volumeClaimTemplate:
        metadata:
          name: clients-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
