apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: twitter-app-deployment-image-update-start
  labels:
    app: tealc
    project: tealc
spec:
  pipelineRef:
    name: twitter-app-deployment-image-update-pipeline
  serviceAccountName: pipeline
  workspaces:
    - name: pipeline-ws
      volumeClaimTemplate:
        metadata:
          name: strimzi-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
